// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Flipkart.FeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("FlipkartDashboard")]
    public partial class FlipkartDashboardFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FlipkartDashboard.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FlipkartDashboard", "\tTest the Flipkart dashboard page", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart logo .")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartLogo_(string email, string password, string phone, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart logo .", null, @__tags);
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
  testRunner.Then("Verify Flipkart logo on left top of home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Search Bar.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", "Phone", new string[] {
                "source:Flipkart_Data.xlsx:SearchData"}, Category="source:Flipkart_Data.xlsx:SearchData")]
        public virtual void ToCheckTheFlipkartSearchBar_(string email, string password, string phone, string product, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Search Bar.", null, exampleTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 17
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
  testRunner.Then(string.Format("verify Search bar by entering product name {0} on search bar .", product), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart My profile section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartMyProfileSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart My profile section under Login dropdown.", null, exampleTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 27
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 29
  testRunner.And("click on My profile  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
  testRunner.Then("verify My profile page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Supercoin Zone section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartSupercoinZoneSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Supercoin Zone section under Login dropdown.", null, exampleTags);
#line 38
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 39
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 41
  testRunner.And("click on Supercoin Zone  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
  testRunner.Then("verify Supercoin Zone page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Plus Zone section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartPlusZoneSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Plus Zone section under Login dropdown.", null, exampleTags);
#line 50
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 51
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
  testRunner.And("click on Flipkart Plus Zone  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
  testRunner.Then("verify Plus Zone page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart orders section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartOrdersSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart orders section under Login dropdown.", null, exampleTags);
#line 62
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 63
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
  testRunner.And("click on Flipkart orders  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
  testRunner.Then("verify orders  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart wishlists section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartWishlistsSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart wishlists section under Login dropdown.", null, exampleTags);
#line 74
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 75
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
  testRunner.And("click on Flipkart wishlists  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
  testRunner.Then("verify wishlists  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart My chats section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartMyChatsSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart My chats section under Login dropdown.", null, exampleTags);
#line 86
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 87
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 89
  testRunner.And("click on Flipkart My chats  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
  testRunner.Then("verify My chats  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Coupons section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartCouponsSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Coupons section under Login dropdown.", null, exampleTags);
#line 98
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 99
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 100
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 101
  testRunner.And("click on Flipkart Coupons  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
  testRunner.Then("verify Coupons  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Gift Cards section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartGiftCardsSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Gift Cards section under Login dropdown.", null, exampleTags);
#line 110
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 111
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 112
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
  testRunner.And("click on Flipkart Gift Cards  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
  testRunner.Then("verify Gift Cards  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Notifications section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartNotificationsSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Notifications section under Login dropdown.", null, exampleTags);
#line 122
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 123
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 124
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 125
  testRunner.And("click on Flipkart Notifications  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
  testRunner.Then("verify Notifications  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Logout section under Login dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartLogoutSectionUnderLoginDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Logout section under Login dropdown.", null, exampleTags);
#line 134
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 135
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 136
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 137
  testRunner.And("click on Flipkart Logout  under user\'s name dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
  testRunner.Then("verify Logout  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Become a seller section in right-top of home page.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartBecomeASellerSectionInRight_TopOfHomePage_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Become a seller section in right-top of home page.", null, exampleTags);
#line 146
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 147
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 148
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 149
  testRunner.And("click on Flipkart\'s Become a seller section in home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 150
  testRunner.Then("verify Become a seller  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Notifications Preferences section under More dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartNotificationsPreferencesSectionUnderMoreDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Notifications Preferences section under More dropdown.", null, exampleTags);
#line 158
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 159
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 160
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 161
  testRunner.And("click on Flipkart\'s Notifications Preferences section under More dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
  testRunner.Then("verify Notifications Preferences  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart 24*7 Customer Care section under More dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkart247CustomerCareSectionUnderMoreDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart 24*7 Customer Care section under More dropdown.", null, exampleTags);
#line 170
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 171
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 172
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 173
  testRunner.And("click on Flipkart\'s 24*7 Customer Care section under More dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
  testRunner.Then("verify 24*7 Customer Care  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Advertise section under More dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartAdvertiseSectionUnderMoreDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Advertise section under More dropdown.", null, exampleTags);
#line 182
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 183
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 184
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 185
  testRunner.And("click on Flipkart\'s Advertise section under More dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
  testRunner.Then("verify Advertise  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Download app section under More dropdown.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartDownloadAppSectionUnderMoreDropdown_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Download app section under More dropdown.", null, exampleTags);
#line 194
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 195
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 196
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 197
  testRunner.And("click on Flipkart\'s Download app section under More dropdown.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
  testRunner.Then("verify Download app  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("To check the Flipkart Cart section in right-top of home page.")]
        [NUnit.Framework.TestCaseAttribute("Deepikakumari091999@gmail.com", "Aku#0918", "8340716081", new string[] {
                "source:Flipkart_Data.xlsx:LoginData"}, Category="source:Flipkart_Data.xlsx:LoginData")]
        public virtual void ToCheckTheFlipkartCartSectionInRight_TopOfHomePage_(string email, string password, string phone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To check the Flipkart Cart section in right-top of home page.", null, exampleTags);
#line 206
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 207
  testRunner.When(string.Format("login with correct credentials{0},{1} and {2}", email, password, phone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 208
  testRunner.Then("Flipkart home page should open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 209
  testRunner.And("click on Flipkart\'s Cart section in home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
  testRunner.Then("verify Cart  page.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

